services:

  db:
    image: postgres:18
    container_name: db
    restart: always
    env_file:
      - ./.env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - pg_data:/var/lib/postgres/data
  app:
    build: .
    container_name: app_c
    ports:
      - "8888:8888"
    command: sh -c "alembic upgrade head & python main.py"
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis

  bot:
    build: .
    container_name: bot_c
    command: python bot.py
    volumes:
      - ./:/app
    depends_on:
      - app
      - redis
    restart: always

  redis:
    image: redis:latest
    container_name: redis_c
    ports:
      - "6379:6379"
    # Optional: use volumes for data persistence
    volumes:
      - redis_data:/data
    restart: always

  worker:
    build: .
    container_name: worker_c
    command: celery -A celery_tasks.app:celery_v2_app worker --loglevel=info # Command to start the Celery worker
    depends_on:
      - redis
      - app
    volumes:
      - .:/app
    restart: always

  beat:
    build: .
    container_name: beat_c
    command: celery -A celery_tasks.app:celery_v2_app beat --loglevel=info
    depends_on:
      - redis
      - app
    volumes:
      - .:/app
    restart: always

  flower:
    image: mher/flower:latest
    container_name: flower_c
    ports:
      - "5555:5555"
    depends_on:
      - redis
    # Connect to the Redis broker using the service name 'redis'
    environment:
      CELERY_BROKER_URL: "redis://redis:6379/1"
      FLOWER_PORT: "5555"

volumes:
  pg_data:
  redis_data:
